---
name: backup-s3

on:
  workflow_dispatch:
  schedule:
    # Sundays at 07:00 UTC.
    - cron: "0 7 * * 0"

permissions:
  contents: read

concurrency:
  group: backup-s3-production
  cancel-in-progress: false

jobs:
  backup:
    name: backup S3 bucket
    runs-on: ubuntu-latest
    environment: production
    env:
      BACKUP_PREFIX: backup-manager-v1

    steps:
      - name: configure 90 day backup retention
        uses: usds/cloud-gov-cli@master
        with:
          command: >
            run-task backup-manager
            --wait
            --name s3-retention-${{ github.run_id }}
            --command "retention 90 ${{ env.BACKUP_PREFIX }}/prod/${{ vars.S3_BACKUP_SERVICE_NAME }}/"
          org: gsa-datagov
          space: prod
          user: ${{ secrets.CF_SERVICE_USER }}
          password: ${{ secrets.CF_SERVICE_AUTH }}

      - name: backup source S3 bucket
        uses: usds/cloud-gov-cli@master
        with:
          command: >
            run-task backup-manager
            --wait
            --name backup-s3-${{ github.run_id }}
            --command "backup s3 ${{ vars.S3_BACKUP_SERVICE_NAME }}"
          org: gsa-datagov
          space: prod
          user: ${{ secrets.CF_SERVICE_USER }}
          password: ${{ secrets.CF_SERVICE_AUTH }}
